#name: mlops_template_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

#pool:
#  name: Demo123

trigger:
 branches:
   include:
     - release*
     - main
pr:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: ResTri
      type: github
      name: KIRTHISHKT/ResourceTrigger
      endpoint: github.com_KIRTHISHKT
      ref: $(Build.SourceBranch)
    - repository: templaterepository
      type: github
      name: KIRTHISHKT/templaterepo
      endpoint: github.com_KIRTHISHKT
      ref: main

extends:
  template: stage123.yml@templaterepository  # Template reference 
