name: mlops_template_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

pool:
  name: Demo123

trigger:
  branches:
    include:
    - release*
pr:
  branches:
    include:
    - main

resources:
  repositories:
  - repository: ResourceTrigger
    type: github
    name: KIRTHISHKT/ResourceTrigger
    endpoint: github.com_KIRTHISHKT
    ref: $(Build.SourceBranch)
  - repository: secondrepo
    type: github
    name: KIRTHISHKT/templaterepo
    endpoint: github.com_KIRTHISHKT
    ref: test

stages:
  - template: /stage.yml@secondrepo
